### ISSUE TITLE
Fichier as.numeric.R ne contient pas de test ni d'exemple

### ISSUE THREAD

**Issue by nicolas95870** [ThinkR-open/thinkr#7]
Fichier as.numeric.R ne contient pas de test ni d'exemple

**Comment by statnmap** [comment]
Could you share the work you did on this issue ?  
Even if it not finished, I'd like to see a PR.
Thanks

**Comment by nicolas95870** [comment]
Sorry, but we add an assert_that to test if the input is a vector or not.  Finally, it's not a good idea because the function can be operate on factor.

**Comment by statnmap** [comment]
factor is a mode for vectors.
You can have a vector of numeric, a vector of factors, a vector of characters.   
I'll let you decide if you want to take a little time to do modifications or let me do the review on the code as is.

**Comment by nicolas95870** [comment]
Ok I made a pull request with unit test, example and assert that if is vector

**Comment by statnmap** [comment]
Merged; Thank you for your contribution.
